Fix functional qDebug() override for Qt 6.12
This fixes the following build error with Qt 6.12.0 and GCC 16:

qrangemodel_impl.h:958:21:
    error: there are no arguments to ‘qDebug’ that depend on a
    template parameter, so a declaration of ‘qDebug’ must be
    available [-Wtemplate-body]

The reason is that Qt 6.12.0 introduced a functional qDebug() call
into a public header, while alkdebug.h undefines qDebug.

(cherry picked from commit f8485a3b31b5ca3a55bb56b742c65e5d89d3f432)