CI: Fix error "Can not contact kdeinit5!" on Tumbleweed distro
The related error message is:

   kdeinit5_wrapper: Warning: connect(/tmp/runtime-user/kdeinit5__99) failed: :
      Connection refused
   Error: Can not contact kdeinit5!

which is fixed by ignoring the exit code.